### ISSUE TITLE
 UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by alwxkxk** [gfxfundamentals/threejsfundamentals#40]
I try to build the project before translating to Chinese.However it throw error while building:

```
Wrote: out\threejs\lessons\ru\atom.xml
processing:  threejs\lessons\ru\index.md
Wrote: out\threejs\lessons\ru\index.html
Processing Lang: zh_cn
----> out\threejs\lessons\screenshots\threejs-fundamentals_zh_cn.jpg
processing:  threejs/lessons/zh_cn/threejs-fundamentals.md
Wrote: out\threejs\lessons\zh_cn\threejs-fundamentals.html
(node:5000) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
  at makeHueFromStr (D:\nodejs\threejsfundamentals\node_modules\@gfxfundamentals\thumbnail-gen\thumbnail-gen.js:54:36)
  at genThumbnail (D:\nodejs\threejsfundamentals\node_modules\@gfxfundamentals\thumbnail-gen\thumbnail-gen.js:110:38)
  at applyTemplateToFiles (D:\nodejs\threejsfundamentals\node_modules\@gfxfundamentals\lesson-builder\build.js:666:9)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at Builder.process (D:\nodejs\threejsfundamentals\node_modules\@gfxfundamentals\lesson-builder\build.js:725:5)
  at main (D:\nodejs\threejsfundamentals\node_modules\@gfxfundamentals\lesson-builder\build.js:953:7)

(node:5000) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:5000) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by greggman** [comment]
Just a guess, did you accidentally translate the front matter keywords at the top of an article?

Or have you not made any changes yet?

At the top of each .md file there are 3 keywords and a blank line. Example from `threejs/lessons/zh_cn/threejs-prerequisites.md`

```
Title: Three.js先决条件
Description: 使用此网站你需要了解的。
TOC: 先决条件

```

The part before the colon `:` needs to stay English. Change only the part after the colon

```
Title: <translate this part>
Description: <translate this part>
TOC: <translate this part>

```

**Comment by alwxkxk** [comment]
Yes, I write some text on the top at  `threejs/lessons/zh_cn/threejs-load-obj.md` by accident.
Thanks.
